#!/usr/bin/env php
<?php
require __DIR__ . '/bootstrap.php';

DI::set('Console', function($c) {
	return new Hail\Console\Application(
            'Hail Framework',
            Config::get('env.version')
    );
});

Console::run();