<?php return array (
  'Debugger' => '\\Hail\\Tracy\\Debugger',
  'Acl' => '\\Hail\\Facades\\Acl',
  'Alias' => '\\Hail\\Facades\\Alias',
  'Application' => '\\Hail\\Facades\\Application',
  'Browser' => '\\Hail\\Facades\\Browser',
  'Cache' => '\\Hail\\Facades\\Cache',
  'CachedDB' => '\\Hail\\Facades\\CachedDB',
  'Config' => '\\Hail\\Facades\\Config',
  'Console' => '\\Hail\\Facades\\Console',
  'Cookie' => '\\Hail\\Facades\\Cookie',
  'DB' => '\\Hail\\Facades\\DB',
  'Event' => '\\Hail\\Facades\\Event',
  'I18N' => '\\Hail\\Facades\\I18N',
  'Library' => '\\Hail\\Facades\\Library',
  'Model' => '\\Hail\\Facades\\Model',
  'Output' => '\\Hail\\Facades\\Output',
  'Request' => '\\Hail\\Facades\\Request',
  'Response' => '\\Hail\\Facades\\Response',
  'Router' => '\\Hail\\Facades\\Router',
  'Session' => '\\Hail\\Facades\\Session',
  'Template' => '\\Hail\\Facades\\Template',
  'Trace' => '\\Hail\\Facades\\Trace',
  'DI' => '\\Hail\\Facades\\DI',
);