<?php return array (
  'acl' => '\\Hail\\Facades\\Acl',
  'alias' => '\\Hail\\Facades\\Alias',
  'app' => '\\Hail\\Facades\\Application',
  'browser' => '\\Hail\\Facades\\Browser',
  'cache' => '\\Hail\\Facades\\Cache',
  'cdb' => '\\Hail\\Facades\\CachedDB',
  'config' => '\\Hail\\Facades\\Config',
  'console' => '\\Hail\\Facades\\Console',
  'cookie' => '\\Hail\\Facades\\Cookie',
  'db' => '\\Hail\\Facades\\DB',
  'event' => '\\Hail\\Facades\\Event',
  'i18n' => '\\Hail\\Facades\\I18N',
  'lib' => '\\Hail\\Facades\\Library',
  'model' => '\\Hail\\Facades\\Model',
  'output' => '\\Hail\\Facades\\Output',
  'request' => '\\Hail\\Facades\\Request',
  'response' => '\\Hail\\Facades\\Response',
  'router' => '\\Hail\\Facades\\Router',
  'session' => '\\Hail\\Facades\\Session',
  'template' => '\\Hail\\Facades\\Template',
  'trace' => '\\Hail\\Facades\\Trace',
);