<?php
namespace Hail\Debugger;

/**
 * Creates a image resource with the error text.
 *
 * @param int $code
 * @param string $message
 *
 * @return resource
 */
function createImage($code, $message)
{
    $size = 200;
    $image = \imagecreatetruecolor($size, $size);
    $textColor = \imagecolorallocate($image, 255, 255, 255);
    \imagestring($image, 5, 10, 10, "Error $code", $textColor);
    foreach (\str_split($message, (int) ($size / 10)) as $line => $text) {
        \imagestring($image, 5, 10, ($line * 18) + 28, $text, $textColor);
    }

    return $image;
}

$fun = '\\' . $template;

if (\function_exists($fun)) {
    $image = createImage($code, $message);
    $fun($image);

    \imagedestroy($image);
}